services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "80:80"
    restart: always
